### ISSUE TITLE
Can't get any data: Signal: null

### ISSUE THREAD

**Issue by TvrdikM** [AllMightySauron/homebride-solaxcloud-api#9]
Hello, from today morning I can't get any data from my Solax. I get these messages:

[11/05/2024, 21:25:53] [homebridge-solaxcloud-api] Child bridge process ended
[11/05/2024, 21:25:53] [homebridge-solaxcloud-api] Process Ended. Code: 1, Signal: null

Error: listen EADDRINUSE: address already in use :::54737
    at Server.setupListenHandle [as _listen2] (node:net:1872:16)
    at listenInCluster (node:net:1920:12)
    at Server.listen (node:net:2008:7)
    at EventedHTTPServer.listen (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:164:20)
    at HAPServer.listen (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:377:21)
    at Bridge.<anonymous> (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1368:18)
    at step (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:195:27)
    at Object.next (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:176:57)
    at fulfilled (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:166:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

Where may be the problem? I didn't make any changes in Homebridge or Solaxcloud.

UPDATE: When i added a bridge again, it works....

Plugin Version v2.3.1 **:
Homebridge Version  v1.8.1
Node.js Version v20.10.0 
Operating System: Raspbian

**Comment by AllMightySauron** [comment]
Hi, 

It doesn't look like a plug-in problem (mine is working fine and it seems like a homebridge issue).

Can you please verify if the condition still holds? 

Thanks
